name: "Master CI/CD"
run-name: "master Ci/CD runned by: ${{ github.actor}}"

on:
    push:
        branches:
            - "main"
# scheduling initial job
jobs:
    first-job:
        run-on: ubuntu-latest
        steps:
            - name: "greeting"
              run: echo "my name is ${{ github.actor}}" 

              