# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
##----------------------------------------------------#
# The jobs are running in parallel without dependency on other
# name: "Master CI/CD"
# run-name: "master Ci/CD runned by: ${{ github.actor}}"

# on:
#     push:
#         branches:
#             - "main"
# # scheduling initial job
# jobs:
#     first-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     Second-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     Third-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

##=======================================#
# running  the jobs in particular sequence
# name: "Master CI/CD"
# run-name: "master Ci/CD runned by: ${{ github.actor}}"

# on:
#     push:
#         branches:
#             - "main"
# # scheduling initial job
# jobs:
#     first-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     first-second-job:
#         runs-on: ubuntu-latest
#         needs: [first-job]
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     Second-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     Third-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

#==================================================

# multiple job dependency and adding more steps to existing task

# name: "Master CI/CD"
# run-name: "master Ci/CD runned by: ${{ github.actor}}"

# on:
#     push:
#         branches:
#             - "main"
# # scheduling initial job
# jobs:
#     first-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

#     Second-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#             - name: "Bye"
#               run : echo "Bye for second job"
#     Third-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#             - name: "Bye"
#               run: echo "Bye for third job"
#             - name: "exit the jobs"
#               run: echo "all jobs are done"

#     first-second-job:
#         runs-on: ubuntu-latest
#         needs: [first-job,Second-job,Third-job]
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

#======================================================

# Multiple sequential and dependency jobs
# name: "Master CI/CD"
# run-name: "master Ci/CD runned by: ${{ github.actor}}"

# on:
#     push:
#         branches:
#             - "main"
# # scheduling initial job
# jobs:
#     first-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

#     Second-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#             - name: "Bye"
#               run : echo "Bye for second job"
#     Third-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#             - name: "Bye"
#               run: echo "Bye for third job"
#             - name: "exit the jobs"
#               run: echo "all jobs are done"

#     first-second-job:
#         runs-on: ubuntu-latest
#         needs: [first-job,Second-job,Third-job]
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"
#     second-second-job:
#         runs-on: ubuntu-latest
#         needs: [first-job,Second-job]
#         steps:
#             - name: "greeting"
#               run: echo "my name is ${{ github.actor}}"

#     third-second-job:
#         runs-on: ubuntu-latest
#         needs: [first-job,Second-job,Third-job,first-second-job]
#         steps:
#             - name: "greeting"
#                 run: echo "my name is ${{ github.actor}}"
#===========================================================

name: "Master CI/CD"
run-name: "master Ci/CD runned by: ${{ github.actor}}"

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened,ready_for_review]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        default: "main"
        required: true
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        # type: environment
        required: true
        type: choice
        options:
        - dev
        - test
        - stage
        - prod
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: "greeting"
              run: echo "my name is ${{ github.actor}}"

    Second-job:
        runs-on: ubuntu-latest
        steps:
            - name: "greeting"
              run: echo "my name is ${{ github.actor}}"
            - name: "Bye"
              run : echo "Bye for second job"
    Third-job:
        runs-on: ubuntu-latest
        steps:
            - name: "greeting"
              run: echo "my name is ${{ github.actor}}"
            - name: "Bye"
              run: echo "Bye for third job"
            - name: "exit the jobs"
              run: echo "all jobs are done"

    first-second-job:
        runs-on: ubuntu-latest
        needs: [first-job,Second-job,Third-job]
        steps:
            - name: "greeting"
              run: echo "my name is ${{ github.actor}}"
